# binjari 웹서버 셋업 — venv / 의존성 / 실행 런처 / 바탕화면 아이콘 (멱등)
# 사용: powershell -NoProfile -ExecutionPolicy Bypass -File setup.ps1 [-Venv] [-NoIcon]
param(
    [switch]$Venv,     # 강제로 .venv 생성·사용 (기본: 시스템 python 에 의존성 있으면 그대로 사용)
    [switch]$NoIcon    # 바탕화면 아이콘 생성 생략
)
$ErrorActionPreference = "Stop"
$root = (Resolve-Path (Join-Path $PSScriptRoot "..\..\..\..")).Path
Write-Host "[binjari_setup] project root: $root"

# pyproject.toml dependencies 와 동기 유지할 것 (+ dev 편의용 uvicorn[standard])
$deps = @(
    "fastapi", "uvicorn[standard]", "aiohttp",
    "platformdirs", "playwright==1.55", "playwright-stealth",
    "pydantic", "python-dotenv", "pyyaml", "requests", "rich", "tenacity", "tzdata"
)

# ── 1) python 결정: .venv 있으면 사용, -Venv 이거나 시스템 python 에 핵심 dep 없으면 생성 ──
$venvDir = Join-Path $root ".venv"
$venvPy = Join-Path $venvDir "Scripts\python.exe"
$useVenv = $false
if (Test-Path $venvPy) {
    $useVenv = $true
} elseif ($Venv) {
    Write-Host "[binjari_setup] .venv 생성 중..."
    python -m venv $venvDir
    $useVenv = $true
} else {
    python -c "import fastapi, uvicorn, playwright, pydantic, dotenv, aiohttp" 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[binjari_setup] 시스템 python 에 의존성 부족 → .venv 생성"
        python -m venv $venvDir
        $useVenv = $true
    }
}
$py = "python"
if ($useVenv) { $py = $venvPy }
Write-Host "[binjari_setup] python: $py (venv=$useVenv)"

# ── 2) 의존성 설치 (이미 충족된 항목은 pip 이 skip — 멱등) ──
& $py -m pip install --disable-pip-version-check -q --upgrade pip
& $py -m pip install --disable-pip-version-check -q @deps
if ($LASTEXITCODE -ne 0) { throw "pip install 실패" }
Write-Host "[binjari_setup] 의존성 OK"

# ── 3) 실행 런처 생성 (안 떠 있으면 백그라운드 기동 후 브라우저 열기) ──
$pyw = "pythonw"
if ($useVenv) { $pyw = Join-Path $venvDir "Scripts\pythonw.exe" }
$bat = Join-Path $root "launch_binjari.bat"
@"
@echo off
rem binjari launcher (generated by binjari_setup skill)
cd /d "%~dp0"
powershell -NoProfile -Command "`$l = Get-NetTCPConnection -LocalPort 8001 -State Listen -ErrorAction SilentlyContinue; if (-not `$l) { Start-Process -WindowStyle Hidden -FilePath '$pyw' -ArgumentList '-m','uvicorn','web_server:app','--host','0.0.0.0','--port','8001'; Start-Sleep -Seconds 4 }"
start "" http://localhost:8001
"@ | Out-File -FilePath $bat -Encoding ascii
Write-Host "[binjari_setup] 런처: $bat"

# ── 4) 바탕화면 아이콘 ──
if (-not $NoIcon) {
    $desktop = [Environment]::GetFolderPath("Desktop")
    $ws = New-Object -ComObject WScript.Shell
    $lnk = Join-Path $desktop "binjari.lnk"
    $sc = $ws.CreateShortcut($lnk)
    $sc.TargetPath = $bat
    $sc.WorkingDirectory = $root
    $sc.Description = "binjari - KTX 빈자리 감시·예매 웹서버"
    $chrome = @(
        "$env:ProgramFiles\Google\Chrome\Application\chrome.exe",
        "${env:ProgramFiles(x86)}\Google\Chrome\Application\chrome.exe",
        "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe"
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1
    if ($chrome) { $sc.IconLocation = "$chrome,0" }
    else { $sc.IconLocation = "$env:SystemRoot\System32\shell32.dll,13" }
    $sc.Save()
    Write-Host "[binjari_setup] 바탕화면 아이콘: $lnk"
}

# ── 5) .env.azure 로 Teams/Azure OAuth 초기화 ──
# azure_env_export 스킬이 만든 .env.azure (AZURE_* + DB_PATH) 가 프로젝트 루트에 있으면
# .env.ktx 에 병합한다. .env.ktx 가 없으면 .env.ktx.example 복사로 먼저 생성 (신규 PC 초기화).
$envAzure = Join-Path $root ".env.azure"
$envKtx = Join-Path $root ".env.ktx"
$envExample = Join-Path $root ".env.ktx.example"
if (-not (Test-Path $envKtx)) {
    if (Test-Path $envExample) {
        Copy-Item $envExample $envKtx
        Write-Host "[binjari_setup] .env.ktx 없음 → .env.ktx.example 복사로 생성 (<...> 자리표시자는 웹 환경 설정에서 입력)"
    }
}
if ((Test-Path $envAzure) -and (Test-Path $envKtx)) {
    $azure = @{}
    foreach ($line in Get-Content $envAzure -Encoding UTF8) {
        # AZURE_* 와 DB_PATH 만 취한다 (다른 키가 섞여 있어도 무시)
        if ($line -match '^\s*(AZURE_[A-Z_]+|DB_PATH)\s*=\s*(.*)$') {
            $azure[$Matches[1]] = $Matches[2].Trim()
        }
    }
    # DB_PATH 의 폴더가 이 PC 에 없으면 프로젝트 기준 기본 경로로 대체
    if ($azure.ContainsKey("DB_PATH")) {
        $dbDir = Split-Path -Parent $azure["DB_PATH"]
        if (-not (Test-Path $dbDir)) {
            $azure["DB_PATH"] = ((Join-Path $root "team_mcp\database\auth.db") -replace '\\', '/')
            Write-Host "[binjari_setup] DB_PATH 경로가 이 PC 에 없어 프로젝트 기본 경로로 대체"
        }
    }
    $lines = @(Get-Content $envKtx -Encoding UTF8)
    $applied = @()
    foreach ($k in @($azure.Keys)) {
        $found = $false
        for ($i = 0; $i -lt $lines.Count; $i++) {
            if ($lines[$i] -match "^\s*$k\s*=") { $lines[$i] = "$k=$($azure[$k])"; $found = $true; break }
        }
        if (-not $found) { $lines += "$k=$($azure[$k])" }
        $applied += $k
    }
    [System.IO.File]::WriteAllLines($envKtx, $lines, (New-Object System.Text.UTF8Encoding $false))
    Write-Host "[binjari_setup] .env.azure 적용 ($($applied.Count)개 키): $($applied -join ', ')"

    # OAuth 토큰 DB 확인
    $db = $azure["DB_PATH"]
    if ($db -and (Test-Path $db)) {
        Write-Host "[binjari_setup] auth.db OK: $db"
    } elseif ($db) {
        Write-Host "[binjari_setup] ⚠ auth.db 없음 ($db) — Teams 알림을 쓰려면 'python -m team_mcp.login' 으로 OAuth 로그인 필요 (korail_alarm 스킬 참고)"
    }
} elseif (-not (Test-Path $envAzure)) {
    Write-Host "[binjari_setup] .env.azure 없음 — Azure/Teams 초기화 건너뜀 (azure_env_export 스킬로 만든 파일을 프로젝트 루트에 두면 자동 적용)"
}

# ── 6) claude CLI 검토 (웹 채팅 도우미 · AI 자동 복구 폴백이 사용) ──
$claude = $null
$cmd = Get-Command claude -ErrorAction SilentlyContinue
if ($cmd) { $claude = $cmd.Source }
if (-not $claude) {
    $cands = @(
        "$env:USERPROFILE\.local\bin\claude.exe",
        "$env:APPDATA\npm\claude.cmd"
    )
    $claude = $cands | Where-Object { Test-Path $_ } | Select-Object -First 1
}
if ($claude) {
    $ver = ""
    try { $ver = (& $claude --version 2>$null | Select-Object -First 1) } catch {}
    Write-Host "[binjari_setup] claude CLI OK: $claude $ver"
} else {
    Write-Host "[binjari_setup] ⚠ claude CLI 없음 — 웹 채팅 도우미와 AI 자동 복구(fable→opus)가 동작하지 않습니다."
    Write-Host "                설치: https://claude.com/claude-code  (설치 후 터미널에서 'claude' 실행해 로그인)"
}

Write-Host "[binjari_setup] 완료 — 바탕화면 'binjari' 더블클릭 → http://localhost:8001"
