# binjari 웹서버 셋업 — venv / 의존성 / 실행 런처 / 바탕화면 아이콘 (멱등)
# 사용: powershell -NoProfile -ExecutionPolicy Bypass -File setup.ps1 [-Venv] [-NoIcon]
param(
    [switch]$Venv,     # 강제로 .venv 생성·사용 (기본: 시스템 python 에 의존성 있으면 그대로 사용)
    [switch]$NoIcon    # 바탕화면 아이콘 생성 생략
)
$ErrorActionPreference = "Stop"
$root = (Resolve-Path (Join-Path $PSScriptRoot "..\..\..\..")).Path
Write-Host "[binjari_setup] project root: $root"

# pyproject.toml dependencies 와 동기 유지할 것 (+ dev 편의용 uvicorn[standard])
$deps = @(
    "fastapi", "uvicorn[standard]", "aiohttp",
    "platformdirs", "playwright==1.55", "playwright-stealth",
    "pydantic", "python-dotenv", "pyyaml", "requests", "rich", "tenacity", "tzdata"
)

# ── 1) python 결정: .venv 있으면 사용, -Venv 이거나 시스템 python 에 핵심 dep 없으면 생성 ──
$venvDir = Join-Path $root ".venv"
$venvPy = Join-Path $venvDir "Scripts\python.exe"
$useVenv = $false
if (Test-Path $venvPy) {
    $useVenv = $true
} elseif ($Venv) {
    Write-Host "[binjari_setup] .venv 생성 중..."
    python -m venv $venvDir
    $useVenv = $true
} else {
    python -c "import fastapi, uvicorn, playwright, pydantic, dotenv, aiohttp" 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[binjari_setup] 시스템 python 에 의존성 부족 → .venv 생성"
        python -m venv $venvDir
        $useVenv = $true
    }
}
$py = "python"
if ($useVenv) { $py = $venvPy }
Write-Host "[binjari_setup] python: $py (venv=$useVenv)"

# ── 2) 의존성 설치 (이미 충족된 항목은 pip 이 skip — 멱등) ──
& $py -m pip install --disable-pip-version-check -q --upgrade pip
& $py -m pip install --disable-pip-version-check -q @deps
if ($LASTEXITCODE -ne 0) { throw "pip install 실패" }
Write-Host "[binjari_setup] 의존성 OK"

# ── 3) 실행 런처 생성 (안 떠 있으면 백그라운드 기동 후 브라우저 열기) ──
$pyw = "pythonw"
if ($useVenv) { $pyw = Join-Path $venvDir "Scripts\pythonw.exe" }
$bat = Join-Path $root "launch_binjari.bat"
@"
@echo off
rem binjari launcher (generated by binjari_setup skill)
cd /d "%~dp0"
powershell -NoProfile -Command "`$l = Get-NetTCPConnection -LocalPort 8001 -State Listen -ErrorAction SilentlyContinue; if (-not `$l) { Start-Process -WindowStyle Hidden -FilePath '$pyw' -ArgumentList '-m','uvicorn','web_server:app','--host','0.0.0.0','--port','8001'; Start-Sleep -Seconds 4 }"
start "" http://localhost:8001
"@ | Out-File -FilePath $bat -Encoding ascii
Write-Host "[binjari_setup] 런처: $bat"

# ── 4) 바탕화면 아이콘 ──
if (-not $NoIcon) {
    $desktop = [Environment]::GetFolderPath("Desktop")
    $ws = New-Object -ComObject WScript.Shell
    $lnk = Join-Path $desktop "binjari.lnk"
    $sc = $ws.CreateShortcut($lnk)
    $sc.TargetPath = $bat
    $sc.WorkingDirectory = $root
    $sc.Description = "binjari - KTX 빈자리 감시·예매 웹서버"
    $chrome = @(
        "$env:ProgramFiles\Google\Chrome\Application\chrome.exe",
        "${env:ProgramFiles(x86)}\Google\Chrome\Application\chrome.exe",
        "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe"
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1
    if ($chrome) { $sc.IconLocation = "$chrome,0" }
    else { $sc.IconLocation = "$env:SystemRoot\System32\shell32.dll,13" }
    $sc.Save()
    Write-Host "[binjari_setup] 바탕화면 아이콘: $lnk"
}

# ── 5) claude CLI 검토 (웹 채팅 도우미 · AI 자동 복구 폴백이 사용) ──
$claude = $null
$cmd = Get-Command claude -ErrorAction SilentlyContinue
if ($cmd) { $claude = $cmd.Source }
if (-not $claude) {
    $cands = @(
        "$env:USERPROFILE\.local\bin\claude.exe",
        "$env:APPDATA\npm\claude.cmd"
    )
    $claude = $cands | Where-Object { Test-Path $_ } | Select-Object -First 1
}
if ($claude) {
    $ver = ""
    try { $ver = (& $claude --version 2>$null | Select-Object -First 1) } catch {}
    Write-Host "[binjari_setup] claude CLI OK: $claude $ver"
} else {
    Write-Host "[binjari_setup] ⚠ claude CLI 없음 — 웹 채팅 도우미와 AI 자동 복구(fable→opus)가 동작하지 않습니다."
    Write-Host "                설치: https://claude.com/claude-code  (설치 후 터미널에서 'claude' 실행해 로그인)"
}

Write-Host "[binjari_setup] 완료 — 바탕화면 'binjari' 더블클릭 → http://localhost:8001"
